import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Preloader } from "@/components/Preloader";
import { SmoothScroll } from "@/components/SmoothScroll";
import { PageTransition } from "@/components/PageTransition";
import { CartProvider } from "@/lib/cart";
import { AuthProvider } from "@/lib/auth";
import { CheckoutCartDrawer } from "@/components/ui/CheckoutCartDrawer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <head>
        <link rel="stylesheet" href="https://widget.meetvolley.com/static/css/widget.css" />
      </head>
      <body className="min-h-dvh">
        <Script
          src="https://widget.meetvolley.com/widget.js"
          strategy="beforeInteractive"
          data-widget="https://api.meetvolley.com/api/widgets/public/912791fc-6310-4ce4-aa83-4e5a8733d225"
        />
        <SmoothScroll />
        <Preloader />
        <AuthProvider>
          <CartProvider>
            <PageTransition>{children}</PageTransition>
            <CheckoutCartDrawer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
